### ISSUE TITLE
Make the background video of the landing page work for iOS mobiles

### ISSUE THREAD

**Issue by amrschmitz** [amrschmitz/incorpus#20]

**Comment by amrschmitz** [comment]
![IMG_3355](https://user-images.githubusercontent.com/36859062/76234018-7672a100-61ff-11ea-9d8d-dc113346a85a.PNG)

It seems that the video works on Android devices but not on iOS devices. The problem is that not only does it not launch the video, but it also doesn't show anything which is a problem.

**Solution 1** would be to display an image if the video doesn't load.
**Solution 2 [preferred]** would be to make the video load even on iOS devices but it might not be feasible.

**Comment by nicofraisse** [comment]
Thanks. Have also noticed that sometimes the video will not play even on desktop unless the 'user interacts with the document first'. While loading the page, I figured that if the user quickly clicks on the video before everything is loaded, it will start playing, as it is considered as interaction.
Console error: `Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
`
